# Generated by Django 2.2 on 2019-05-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iname',
            field=models.CharField(max_length=40),
        ),
    ]
