# Generated by Django 2.2 on 2019-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordernow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Total', models.FloatField()),
            ],
        ),
    ]
